import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header"; // Importing the Header component
import Footer from "@/components/layout/Footer"; // Importing the Footer component

export const metadata: Metadata = {
  title: "weframetech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Container for the entire layout with a maximum width and centered alignment */}
        <div className="max-w-[1600px] mx-auto">
          <Header /> {/* Render the Header component */}
          {children} {/* Render the page-specific content */}
          <Footer /> {/* Render the Footer component */}
        </div>
      </body>
    </html>
  );
}
